In [1]:
import numpy as np

In [8]:
one_to_ten = np.arange(0,10)
test2 = np.arange(0,11,2)
test2

array([ 0,  2,  4,  6,  8, 10])

In [7]:
one_to_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
zero = np.zeros(3)
zero

array([0., 0., 0.])

In [15]:
one = np.ones(3)
one

array([1., 1., 1.])

In [20]:
#對角矩陣
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#在特定範圍分成幾等分
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
#在特定範圍分成幾等分
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [25]:
a = 'My calculation is just to sum each row i.e. 1+3, 2+4, 3+5 and 2+0. I am using the below code' 

In [27]:
a = list(a)
#轉成List
a

['M',
 'y',
 ' ',
 'c',
 'a',
 'l',
 'c',
 'u',
 'l',
 'a',
 't',
 'i',
 'o',
 'n',
 ' ',
 'i',
 's',
 ' ',
 'j',
 'u',
 's',
 't',
 ' ',
 't',
 'o',
 ' ',
 's',
 'u',
 'm',
 ' ',
 'e',
 'a',
 'c',
 'h',
 ' ',
 'r',
 'o',
 'w',
 ' ',
 'i',
 '.',
 'e',
 '.',
 ' ',
 '1',
 '+',
 '3',
 ',',
 ' ',
 '2',
 '+',
 '4',
 ',',
 ' ',
 '3',
 '+',
 '5',
 ' ',
 'a',
 'n',
 'd',
 ' ',
 '2',
 '+',
 '0',
 '.',
 ' ',
 'I',
 ' ',
 'a',
 'm',
 ' ',
 'u',
 's',
 'i',
 'n',
 'g',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'b',
 'e',
 'l',
 'o',
 'w',
 ' ',
 'c',
 'o',
 'd',
 'e']

In [29]:
將重複的字去除
set(a)

{' ',
 '+',
 ',',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 'I',
 'M',
 'a',
 'b',
 'c',
 'd',
 'e',
 'g',
 'h',
 'i',
 'j',
 'l',
 'm',
 'n',
 'o',
 'r',
 's',
 't',
 'u',
 'w',
 'y'}

In [31]:
#知道有幾個不重複的字
len(set(a))

31

In [33]:
a = [1,2,3,4]
b = [1,2,3,5]
#聯集
set(a) | set(b)

{1, 2, 3, 4, 5}

In [34]:
#交集
set(a) & set(b)

{1, 2, 3}

In [35]:
#差集
set(a) - set(b)

{4}

In [36]:
#產生隨機數列
np.random.rand(2)

array([0.56957348, 0.61391272])

In [38]:
#產生 幾 X 幾 隨機數列
np.random.rand(5,5)

array([[0.16587669, 0.38331922, 0.49022105, 0.21081512, 0.61640375],
       [0.99394813, 0.68251238, 0.17001211, 0.24792038, 0.98437002],
       [0.01605164, 0.65553834, 0.23047764, 0.56518093, 0.6274801 ],
       [0.29166387, 0.33232835, 0.33790625, 0.58017185, 0.05743931],
       [0.19920915, 0.40603868, 0.85560276, 0.36035396, 0.07958537]])

In [39]:
#產生隨機整數
np.random.randint(1,100)

29

In [40]:
#產生隨機整數數列，共10個
np.random.randint(1,100,10)

array([22, 21, 18, 23, 89,  5,  7, 52, 77, 21])

In [41]:
#重塑陣列
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)
ranarr

array([33, 30, 35, 23,  3, 32,  0, 29, 22, 24])

In [44]:
#重塑數列，上個arr數目為25個
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
#重塑數列，兩數相乘等於原本數列的數目(上個數列為10個)
ranarr.reshape(5,2)

array([[33, 30],
       [35, 23],
       [ 3, 32],
       [ 0, 29],
       [22, 24]])

In [53]:
#取得極值
ranarr.max()

35

In [54]:
#最大的值得位置在[2](index location)
ranarr.argmax()

2

In [55]:
#取最小值
ranarr.min()

0

In [56]:
#最小值的index location
ranarr.argmin()

6

In [63]:
#取得陣列維度(無重塑，故無第二維)
arr.shape

(25,)

In [59]:
#重塑數列
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [62]:
#重塑數列為(1,25)維度，故回傳(1,25)
arr.reshape(1,25).shape

(1, 25)

In [67]:
test_arr = np.random.rand(10)
test_arr

array([0.97004995, 0.09266847, 0.69145839, 0.77667455, 0.6067289 ,
       0.81196801, 0.54294925, 0.96912938, 0.46191009, 0.86399723])

In [68]:
#取得資料型態
test_arr.dtype

dtype('float64')

In [69]:
#像List一樣可使用[]篩選資料
arr_list = np.arange(0,11)
arr_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr_list[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [71]:
#廣播 (Broadcasting)
arr_Brdg = np.arange(0,11)
arr_Brdg

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
slice_of_arrBrdg = arr_Brdg[0:6]
slice_of_arrBrdg

array([0, 1, 2, 3, 4, 5])

In [73]:
slice_of_arrBrdg[:] = 99
slice_of_arrBrdg

array([99, 99, 99, 99, 99, 99])

In [75]:
#二維資料取值 (是array)
arr_2d = np.array(([10,20,30],[5,10,15],[15,20,25]))
arr_2d

array([[10, 20, 30],
       [ 5, 10, 15],
       [15, 20, 25]])

In [77]:
print("arr_2d[1] ->",arr_2d[1])

#以下相等
print("arr_2d[1][0] ->",arr_2d[1][0])
print("arr_2d[1,0] ->",arr_2d[1,0])

#以下相等
print("arr_2d[2] ->",arr_2d[2])
print("arr_2d[2,:] ->",arr_2d[2,:])


arr_2d[1] -> [ 5 10 15]
arr_2d[1][0] -> 5
arr_2d[1,0] -> 5
arr_2d[2] -> [15 20 25]
arr_2d[2,:] -> [15 20 25]


In [78]:
#用條件篩選資料
arr_if = np.arange(1,11)
arr_if > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
arr_over_four = arr_if > 4
arr_over_four

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [81]:
arr_if[arr_over_four]

array([ 5,  6,  7,  8,  9, 10])

In [82]:
arr_if[arr_if>4]

array([ 5,  6,  7,  8,  9, 10])

In [86]:
# numpy 計算
arr_calculate = np.arange(0,10)
print(arr)
arr + arr 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [85]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])

In [87]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [90]:
#因為0 / 0 會報錯
arr/arr

c:\users\jun\pycharmproject\python_machinelearning\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [91]:
#因為arr包含0，所以會出錯
1 / arr

c:\users\jun\pycharmproject\python_machinelearning\venv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158,
       0.05      , 0.04761905, 0.04545455, 0.04347826, 0.04166667])

In [92]:
#三次方
arr ** 3

array([    0,     1,     8,    27,    64,   125,   216,   343,   512,
         729,  1000,  1331,  1728,  2197,  2744,  3375,  4096,  4913,
        5832,  6859,  8000,  9261, 10648, 12167, 13824], dtype=int32)

In [99]:
#nunpy內建函數
print('平方根')
np.sqrt(arr)

平方根


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [95]:
print('自然指數')
np.exp(arr)

自然指數


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
       2.64891221e+10])

In [96]:
#因為有0所以出錯
print('log')
np.log(arr)

log


c:\users\jun\pycharmproject\python_machinelearning\venv\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383])

In [97]:
print('最大')
np.max(arr)

最大


24

In [98]:
print('sin')
np.sin(arr)

sin


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])